### ISSUE TITLE
Class methods get wrapped twice

### ISSUE THREAD

**Issue by karimsa** [chpio/babel-plugin-transform-async-to-bluebird#2]
I've experienced a strange bug while trying to use this plugin. I believe it is caused by the wrapping of async class methods twice (seems to stop the coroutine from running).

Here is a sample code snippet that reproduces the bug:

```javascript
class Test {
  async go () {
    console.log('start:go')
    await Promise.resolve('test')
    console.log('end:go')
  }
}

const runGo = () => {
  return (new Test()).go()
}

;(async () => {
  console.log('start:all')
  await runGo()
  console.log('end:all')
})()
```

If you transpile this using the `bluebird` preset (which relies on this plugin) and the `transform-es2015-modules-commonjs` plugin, the resultant code is this:

```javascript
'use strict';

var _bluebird = require('bluebird');

class Test {
  *go() {
    return (0, _bluebird.coroutine)(function* () {
      console.log('start:go');
      yield (0, _bluebird.resolve)((0, _bluebird.resolve)('test'));
      console.log('end:go');
    })();
  }
}

const runGo = () => {
  return new Test().go();
};

(0, _bluebird.coroutine)(function* () {
  console.log('start:all');
  yield (0, _bluebird.resolve)(runGo());
  console.log('end:all');
})();
```

Running this showing the promise never running:

```
start:all
end:all
```

If I simply remove the `*` from the go class method in the transpiled output (and therefore just undo its generatorness - and let it return the coroutine generator instead), this issue goes away and the result is:

```
start:all
start:go
end:go
end:all
```

**Comment by chpio** [comment]
fixed in v1.1.1
